### ISSUE TITLE
Export as cypress script errors in console and does not download

### ISSUE THREAD

**Issue by yharaskrik** [cypress-io/cypress-recorder-extension#11]
When running Export to cypress in the Chrome Recorder devtools I get 
```
Uncaught (in promise) Error: Step.key is not a string
    at L.onResponse (extensions.js:1:20962)
```

Oddly enough exporting to puppeteer throws `Uncaught (in promise) Error: Invalid JSON` but puppeteer replay script works and export as JSON works.

![image](https://user-images.githubusercontent.com/9469090/226985718-750cb844-01f1-4597-aa7e-50e1799bfc82.png)

Version 111.0.5563.110 (Official Build) (arm64)
Extension v: 1.1.1

**Comment by nagash77** [comment]
@yharaskrik can you provide reproduction steps for how you encountered this error?

**Comment by yharaskrik** [comment]
> @yharaskrik can you provide reproduction steps for how you encountered this error?
 
Yup!

For me it was

Open chrome
Go to website
Start recording
Do the steps
End recording
Try to download

**Comment by nagash77** [comment]
@yharaskrik can you specify which site you are going to and what are the steps you are taking in your recording?

**Comment by nagash77** [comment]
Unfortunately we will have to close this due to inactivity.  Please comment back with the requested details and we can revisit.
