### ISSUE TITLE
Add support for Cypress Testing Library

### ISSUE THREAD

**Issue by EvgenyOrekhov** [cypress-io/cypress-recorder-extension#12]
Would be awesome if it could generate [Cypress Testing Library](https://testing-library.com/docs/cypress-testing-library/intro/) queries while following the [priority recommendations](https://testing-library.com/docs/queries/about/#priority), and fall back to `cy.get()` when an element is not accessible.

**Comment by marktnoonan** [comment]
Thanks for this request, I'm going to recommend we close it for now to clean up, as we don't expect to add something this to the extension in the near future. But I do love Testing Library and this is a good idea in general!
