### ISSUE TITLE
Export as cypress test script option not visible 

### ISSUE THREAD

**Issue by AaronVikta** [cypress-io/cypress-recorder-extension#3]
currently there is an issue with the chrome-recorder. [https://bugs.chromium.org/p/chromium/issues/detail?id=1354899](https://t.co/tUMurahz3z)
So, I tried to see what the issue is installing the extension from the github repo. I noticed this error:
Uncaught TypeError: Failed to resolve module specifier "@cypress/chrome-recorder". Relative references must start with either "/", "./", or "../"

![image](https://user-images.githubusercontent.com/21356678/185791007-da0c97c6-b508-411b-bbfd-0afd1d896b2c.png)

**Comment by lostfocus** [comment]
Same here. (I didn't check the errors, I just can't see the export option.) MacOS 12.5/Chrome 104 if that is any help. I did restart both Chrome and the computer and that didn't change anything.

**Comment by fyodorio** [comment]
Same for me, Chrome 105, macOS 12.5.1, can only export to JSON and convert to spec using CLI.

**Comment by kobenguyent** [comment]
I experienced this and sorted it out

https://github.com/puppeteer/replay/issues/453

**Comment by lostfocus** [comment]
Hm. I just updated all the extensions and it's still not working. So I don't know. 🤷‍♂️

**Comment by peterngtr-thomannio** [comment]
I guess the extension is not rolled up before uploading to chrome web store.

**Comment by kobenguyent** [comment]
I think the uploaded package to chrome webstore is not rolled up.

**Comment by mjhenkes** [comment]
@kobenguyent, I think you're right. I'm working on getting privileges to update the extension in the chrome web store.

All: Sorry it's taken us a bit to get to this :(

**Comment by mjhenkes** [comment]
@AaronVikta , @fyodorio , @kobenguyent , @lostfocus, I published a new version 1.1.1 and this issue appears to be fixed now.

**Comment by lostfocus** [comment]
It is still not showing up for me:

<img width="333" alt="Screenshot 2023-03-09 at 15 40 30" src="https://user-images.githubusercontent.com/45055/224058953-686516b5-4763-4872-9b63-480274abb14e.png">

<img width="418" alt="Screenshot 2023-03-09 at 15 40 14" src="https://user-images.githubusercontent.com/45055/224058882-63ed9e43-ef85-4c79-a9e4-2a2bf32b5d60.png">

<img width="302" alt="Screenshot 2023-03-09 at 15 40 49" src="https://user-images.githubusercontent.com/45055/224058973-34a7d522-b491-4c81-9535-c25074aac67a.png">

**Comment by mjhenkes** [comment]
@lostfocus, have you tried restarting your browser? It's showing up for me now where as before I would get the same error that you did.



![Image](https://user-images.githubusercontent.com/1588747/224063687-2dbc20b4-9f10-4642-9823-03df48de6e3e.png)

**Comment by lostfocus** [comment]
Yes. I even tried deleting and reinstalling from the store and restarting Chrome after that. Same result. No error message, though - nothing in the console, either.

**Comment by lostfocus** [comment]
I just disabled all other extensions to make sure they don't interfere and restarted Chrome - same effect.

**Comment by peterngtr-thomannio** [comment]
Let’s enable debugging and check what is the error. 😄

**Comment by kobenguyent** [comment]
@lostfocus lets enable debug and check the error if any

**Comment by fyodorio** [comment]
It works for me now guys, thanks 👍

**Comment by lostfocus** [comment]
I honestly have no clue how to enable debug for Chrome extensions 🤷 I switched to Developer mode and enabled "Collect errors" but I don't see anything anywhere

**Comment by lostfocus** [comment]
Uhm. 

At what point does it add the option to the dropdown? I was trying with my recordings that I have been using manually all the time. I just recorded a new one and the option appeared. So I guess it's just an issue of when it adds the cypress export? And/or a documentation thing?


Update, a few minutes later: The bug is getting more interesting. I closed Chrome and opened it again. The option to export to Cypress was gone again. I recorded a new recording, it came back. Closed and reopened Chrome, gone.


Update yet a few minutes later: the option only shows up when the tab is not a new empty tab when opening the Dev Tools. 
Empty Tab -> Open Dev Tools: not there  
Tab with a website -> Open Dev Tools: there it is

**Comment by AaronVikta** [comment]
Works for me now.
@lostfocus what is your Chrome version?
Just wondering if you might be running an older version of Chrome.

**Comment by lostfocus** [comment]
Nope, the latest version on MacOS.  
Can you try to open the Dev Tools on an empty tab and see if the option is available?

**Comment by AaronVikta** [comment]
Yeah it is available for me.

**Comment by AaronVikta** [comment]
> Nope, the latest version on MacOS. Can you try to open the Dev Tools on an empty tab and see if the option is available?

Yeah, it is available on an empty tab.

**Comment by lostfocus** [comment]
Fascinating 😄 
As far as I'm concerned the ticket can be closed now, I know how to get to it.

**Comment by AaronVikta** [comment]
> Fascinating 😄 As far as I'm concerned the ticket can be closed now, I know how to get to it.

Impressive.
Do you mind sharing the solution you, for anyone that encounters the same issue

**Comment by lostfocus** [comment]
Ah, as I said further up: when I open the Dev Tools in a tab with an already opened website and not in an empty tab, the option is there.
