### ISSUE TITLE
Extension permissions - security risks

### ISSUE THREAD

**Issue by kevinsafon** [cypress-io/cypress-recorder-extension#5]
Hi guys,

thank you very much for providing this great extension! This will make things so much easier for our developpers and business analysts.

I'm reaching out to you because I want to introduce it to the company I work for (Societe Generale, a big bank in France) but the extension didn't go through the security check. The security team found the below vulnerabilities with the extension.

Do you guys think this is excessive or is it something you guys can actually address? Hopefully they can be addressed.

Thank you

![image](https://user-images.githubusercontent.com/6100416/206735581-17519f27-25da-4540-b248-28c33699f259.png)

**Comment by jordanpowell88** [comment]
Hey @kevinsafon thanks for the feedback and we are really happy that the plugin has been valuable for your teams! After looking into this issue we're not quite sure it is fair to categorize these are "security vulnerabilities". We are essentially just wrapping the commands and functionality already provided by the Recorder panel from the Google Chrome DevTools team. It's up to the end users if they want to accept those risks or not and most of those risks depend upon how you use the recording. At this time I don't see any actionable items for us to address here but we appreciate the feedback and hope you continue to find the plugin valuable. Also, we always welcome contributions if you believe there is a way to mitigate these issues in a way that we do not see.
